# kgc_keygen.py
# 金鑰生成中心 (Key Generation Center)
# 使用方式: python kgc_keygen.py --pub public.key --priv private.key --kem ML-KEM-1024

import os, time, json, pickle, argparse
import oqs


def generate_keypair(kem_alg: str, public_key_path: str, private_key_path: str, key_id: str = None):
    """金鑰生成中心：產生ML-KEM密鑰對並分別儲存公私鑰"""
    print(f"🔑 [KGC] 生成 {kem_alg} 密鑰對...")
    
    # 生成密鑰對
    kem = oqs.KeyEncapsulation(kem_alg)
    public_key = kem.generate_keypair()
    private_key = kem.export_secret_key()
    
    # 建立金鑰元數據
    key_metadata = {
        "algorithm": kem_alg,
        "key_id": key_id or f"key_{int(time.time())}",
        "created_at": int(time.time()),
        "version": 1,
        "key_size": len(public_key),
        "description": f"ML-KEM keypair generated by KGC"
    }
    
    # 儲存公鑰檔案（含元數據）
    public_key_data = {
        "metadata": key_metadata,
        "public_key": public_key
    }
    with open(public_key_path, "wb") as f:
        pickle.dump(public_key_data, f, protocol=pickle.HIGHEST_PROTOCOL)
    
    # 儲存私鑰檔案（含元數據）
    private_key_data = {
        "metadata": key_metadata,
        "private_key": private_key
    }
    with open(private_key_path, "wb") as f:
        pickle.dump(private_key_data, f, protocol=pickle.HIGHEST_PROTOCOL)
    
    # 生成金鑰資訊報告
    report = {
        "key_id": key_metadata['key_id'],
        "algorithm": kem_alg,
        "public_key_file": public_key_path,
        "private_key_file": private_key_path,
        "public_key_size": len(public_key),
        "private_key_size": len(private_key),
        "created_at": key_metadata['created_at']
    }
    
    report_path = f"{key_metadata['key_id']}_report.json"
    with open(report_path, "w", encoding='utf-8') as f:
        json.dump(report, f, indent=2, ensure_ascii=False)
    
    print(f"📤 公鑰檔案: {public_key_path} ({len(public_key)} bytes)")
    print(f"📥 私鑰檔案: {private_key_path} ({len(private_key)} bytes)")
    print(f"📋 金鑰報告: {report_path}")
    print(f"🆔 金鑰ID: {key_metadata['key_id']}")
    print(f"⏰ 生成時間: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(key_metadata['created_at']))}")
    
    kem.free()
    return key_metadata['key_id']


def verify_keypair(public_key_path: str, private_key_path: str):
    """驗證密鑰對是否匹配"""
    print("🔍 驗證密鑰對...")
    
    try:
        # 載入公鑰
        with open(public_key_path, "rb") as f:
            pub_data = pickle.load(f)
        
        # 載入私鑰
        with open(private_key_path, "rb") as f:
            priv_data = pickle.load(f)
        
        # 檢查元數據是否匹配
        if pub_data['metadata']['key_id'] != priv_data['metadata']['key_id']:
            print("❌ 金鑰ID不匹配")
            return False
        
        # 進行封裝測試
        kem_alg = pub_data['metadata']['algorithm']
        public_key = pub_data['public_key']
        private_key = priv_data['private_key']
        
        # 重建私鑰物件
        kem = oqs.KeyEncapsulation(kem_alg)
        kem.import_secret_key(private_key)
        
        # 測試封裝/解封裝
        with oqs.KeyEncapsulation(kem_alg) as encap:
            encapsulated_key, shared_secret1 = encap.encap_secret(public_key)
        
        shared_secret2 = kem.decap_secret(encapsulated_key)
        
        if shared_secret1 == shared_secret2:
            print("✅ 密鑰對驗證成功")
            print(f"🆔 金鑰ID: {pub_data['metadata']['key_id']}")
            print(f"🔧 演算法: {kem_alg}")
            kem.free()
            return True
        else:
            print("❌ 共享秘密不匹配")
            kem.free()
            return False
            
    except Exception as e:
        print(f"❌ 驗證失敗: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(description="ML-KEM 金鑰生成中心 (KGC)")
    subparsers = parser.add_subparsers(dest="command", help="操作模式")

    # 生成密鑰對
    gen_parser = subparsers.add_parser("generate", help="生成新的密鑰對")
    gen_parser.add_argument("--pub", required=True, help="公鑰輸出路徑")
    gen_parser.add_argument("--priv", required=True, help="私鑰輸出路徑")
    gen_parser.add_argument("--kem", default="ML-KEM-1024", 
                           choices=["ML-KEM-512", "ML-KEM-768", "ML-KEM-1024"],
                           help="KEM演算法")
    gen_parser.add_argument("--key-id", help="自訂金鑰ID")

    # 驗證密鑰對
    verify_parser = subparsers.add_parser("verify", help="驗證密鑰對")
    verify_parser.add_argument("--pub", required=True, help="公鑰檔案路徑")
    verify_parser.add_argument("--priv", required=True, help="私鑰檔案路徑")

    # 檢視金鑰資訊
    info_parser = subparsers.add_parser("info", help="檢視金鑰資訊")
    info_parser.add_argument("--key", required=True, help="金鑰檔案路徑")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return

    try:
        if args.command == "generate":
            key_id = generate_keypair(
                kem_alg=args.kem,
                public_key_path=args.pub,
                private_key_path=args.priv,
                key_id=args.key_id
            )
            print(f"\n📋 分發說明:")
            print(f"  🔓 將公鑰檔案 {args.pub} 安全分發給加密方")
            print(f"  🔐 將私鑰檔案 {args.priv} 安全分發給解密方")
            print(f"  ⚠️ 私鑰檔案必須保密，不得外洩！")

        elif args.command == "verify":
            success = verify_keypair(args.pub, args.priv)
            if not success:
                exit(1)

        elif args.command == "info":
            with open(args.key, "rb") as f:
                key_data = pickle.load(f)
            
            metadata = key_data['metadata']
            key_type = "公鑰" if 'public_key' in key_data else "私鑰"
            key_size = len(key_data.get('public_key', key_data.get('private_key', b'')))
            
            print(f"📋 金鑰資訊:")
            print(f"  類型: {key_type}")
            print(f"  ID: {metadata['key_id']}")
            print(f"  演算法: {metadata['algorithm']}")
            print(f"  大小: {key_size} bytes")
            print(f"  版本: {metadata['version']}")
            print(f"  創建時間: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(metadata['created_at']))}")

    except Exception as e:
        print(f"❌ 錯誤: {e}")
        exit(1)


if __name__ == "__main__":
    main()
